#!/usr/bin/env python3

"""
Material Dark theme generator.
"""

from utils import print_theme, SOLID_ALPHA
from utils.material import *

ACCENT_COLOR = BLUE_A200
LIGHT_ACCENT_COLOR = BLUE_A100

SOLID_ACCENT_COLOR = ACCENT_COLOR | SOLID_ALPHA
SOLID_LIGHT_ACCENT_COLOR = LIGHT_ACCENT_COLOR | SOLID_ALPHA

PRIMARY_TEXT_COLOR = LIGHT_TEXT_COLOR | LIGHT_TEXT_PRIMARY_ALPHA
SECONDARY_TEXT_COLOR = LIGHT_TEXT_COLOR | LIGHT_TEXT_SECONDARY_ALPHA

ACTIVE_ICON_COLOR = LIGHT_ICON_COLOR | LIGHT_ICON_ACTIVE_ALPHA
APP_BAR_COLOR = DARK_APP_BAR_COLOR | SOLID_ALPHA
BACKGROUND_COLOR = DARK_BACKGROUND_COLOR | SOLID_ALPHA
DIVIDER_COLOR = LIGHT_TEXT_COLOR | LIGHT_TEXT_DIVIDER_ALPHA
HINT_COLOR = LIGHT_TEXT_COLOR | LIGHT_TEXT_HINT_ALPHA
LIGHT_SELECTED_COLOR = LIGHT_TEXT_COLOR | RIPPLE_ALPHA

THEME = [
    ("actionBarActionModeDefault", APP_BAR_COLOR),
    ("actionBarActionModeDefaultIcon", ACTIVE_ICON_COLOR),
    ("actionBarActionModeDefaultTop", DARK_STATUS_BAR_COLOR | SOLID_ALPHA),
    ("actionBarDefault", APP_BAR_COLOR),
    ("actionBarDefaultIcon", ACTIVE_ICON_COLOR),
    ("actionBarDefaultSearch", PRIMARY_TEXT_COLOR),
    ("actionBarDefaultSearchPlaceholder", HINT_COLOR),
    ("actionBarDefaultSelector", LIGHT_SELECTED_COLOR),
    ("actionBarDefaultSubtitle", SECONDARY_TEXT_COLOR),
    ("actionBarDefaultTitle", PRIMARY_TEXT_COLOR),
    ("avatar_actionBarIconBlue", ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconCyan", ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconGreen", ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconOrange", ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconPink", ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconRed", ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconViolet", ACTIVE_ICON_COLOR),
    ("avatar_actionBarSelectorBlue", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorCyan", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorGreen", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorOrange", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorPink", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorRed", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorViolet", LIGHT_SELECTED_COLOR),
    ("avatar_backgroundActionBarBlue", BLUE_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarCyan", CYAN_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarGreen", GREEN_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarOrange", ORANGE_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarPink", PINK_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarRed", RED_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarViolet", PURPLE_900 | SOLID_ALPHA),
    ("avatar_backgroundBlue", BLUE_500 | SOLID_ALPHA),
    ("avatar_backgroundCyan", CYAN_700 | SOLID_ALPHA),
    ("avatar_backgroundGreen", GREEN_500 | SOLID_ALPHA),
    ("avatar_backgroundOrange", ORANGE_800 | SOLID_ALPHA),
    ("avatar_backgroundPink", PINK_500 | SOLID_ALPHA),
    ("avatar_backgroundRed", RED_500 | SOLID_ALPHA),
    ("avatar_backgroundViolet", PURPLE_500 | SOLID_ALPHA),
    ("avatar_nameInMessageBlue", BLUE_400 | SOLID_ALPHA),
    ("avatar_nameInMessageCyan", CYAN_500| SOLID_ALPHA),
    ("avatar_nameInMessageGreen", GREEN_500 | SOLID_ALPHA),
    ("avatar_nameInMessageOrange", ORANGE_500 | SOLID_ALPHA),
    ("avatar_nameInMessagePink", PINK_200 | SOLID_ALPHA),
    ("avatar_nameInMessageRed", RED_300 | SOLID_ALPHA),
    ("avatar_nameInMessageViolet", PURPLE_200 | SOLID_ALPHA),
    ("avatar_subtitleInProfileBlue", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileCyan", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileGreen", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileOrange", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfilePink", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileRed", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileViolet", SECONDARY_TEXT_COLOR),
    ("avatar_text", PRIMARY_TEXT_COLOR),
    ("chat_botButtonText", PRIMARY_TEXT_COLOR),
    ("chat_botProgress", ACTIVE_ICON_COLOR),
    ("chat_editDoneIcon", ACTIVE_ICON_COLOR),
    ("chat_goDownButton", LIGHT_BACKGROUND_COLOR | SOLID_ALPHA),
    ("chat_goDownButtonCounter", PRIMARY_TEXT_COLOR),
    ("chat_goDownButtonCounterBackground", SOLID_ACCENT_COLOR),
    ("chat_goDownButtonIcon", DARK_TEXT_COLOR | DARK_ICON_ACTIVE_ALPHA),
    ("chat_goDownButtonShadow", BACKGROUND_COLOR),
    ("chat_inAudioDurationSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_inAudioDurationText", SECONDARY_TEXT_COLOR),
    ("chat_inBubble", DARK_CARD_COLOR | SOLID_ALPHA),
    ("chat_inBubbleSelected", LIGHT_SELECTED_COLOR),
    ("chat_inBubbleShadow", BACKGROUND_COLOR),
    ("chat_inContactNameText", PRIMARY_TEXT_COLOR),
    ("chat_inContactPhoneText", SECONDARY_TEXT_COLOR),
    ("chat_inFileInfoSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_inFileInfoText", SECONDARY_TEXT_COLOR),
    ("chat_inFileNameText", PRIMARY_TEXT_COLOR),
    ("chat_inInstant", ACTIVE_ICON_COLOR),
    ("chat_inInstantSelected", ACTIVE_ICON_COLOR),
    ("chat_inLoader", ACTIVE_ICON_COLOR),
    ("chat_inLoaderSelected", ACTIVE_ICON_COLOR),
    ("chat_inPreviewInstantSelectedText", SOLID_ACCENT_COLOR),
    ("chat_inPreviewInstantText", SOLID_LIGHT_ACCENT_COLOR),
    ("chat_inPreviewLine", SOLID_ACCENT_COLOR),
    ("chat_inReplyLine", SOLID_ACCENT_COLOR),
    ("chat_inReplyMessageText", SECONDARY_TEXT_COLOR),
    ("chat_inReplyNameText", PRIMARY_TEXT_COLOR),
    ("chat_inSiteNameText", PRIMARY_TEXT_COLOR),
    ("chat_inTimeSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_inTimeText", SECONDARY_TEXT_COLOR),
    ("chat_inViews", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_inViewsSelected", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_inVoiceSeekbar", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_inVoiceSeekbarFill", ACTIVE_ICON_COLOR),
    ("chat_inVoiceSeekbarSelected", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_linkSelectBackground", LIGHT_SELECTED_COLOR),
    ("chat_messageLinkIn", SOLID_LIGHT_ACCENT_COLOR),
    ("chat_messageLinkOut", SOLID_LIGHT_ACCENT_COLOR),
    ("chat_messagePanelBackground", DARK_CARD_COLOR | SOLID_ALPHA),
    ("chat_messagePanelHint", HINT_COLOR),
    ("chat_messagePanelIcons", ACTIVE_ICON_COLOR),
    ("chat_messagePanelSend", ACTIVE_ICON_COLOR),
    ("chat_messagePanelShadow", BACKGROUND_COLOR),
    ("chat_messagePanelText", PRIMARY_TEXT_COLOR),
    ("chat_messageTextIn", PRIMARY_TEXT_COLOR),
    ("chat_messageTextOut", PRIMARY_TEXT_COLOR),
    ("chat_muteIcon", ACTIVE_ICON_COLOR),
    ("chat_outAudioDurationSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_outAudioDurationText", SECONDARY_TEXT_COLOR),
    ("chat_outBubble", GREY_700 | SOLID_ALPHA),
    ("chat_outBubbleSelected", LIGHT_SELECTED_COLOR),
    ("chat_outBubbleShadow", BACKGROUND_COLOR),
    ("chat_outContactNameText", PRIMARY_TEXT_COLOR),
    ("chat_outContactPhoneText", SECONDARY_TEXT_COLOR),
    ("chat_outFileInfoSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_outFileInfoText", SECONDARY_TEXT_COLOR),
    ("chat_outFileNameText", PRIMARY_TEXT_COLOR),
    ("chat_outInstant", ACTIVE_ICON_COLOR),
    ("chat_outInstantSelected", ACTIVE_ICON_COLOR),
    ("chat_outLoader", ACTIVE_ICON_COLOR),
    ("chat_outLoaderSelected", ACTIVE_ICON_COLOR),
    ("chat_outMenu", ACTIVE_ICON_COLOR),
    ("chat_outMenuSelected", ACTIVE_ICON_COLOR),
    ("chat_outPreviewInstantSelectedText", SOLID_ACCENT_COLOR),
    ("chat_outPreviewInstantText", SOLID_LIGHT_ACCENT_COLOR),
    ("chat_outPreviewLine", SOLID_ACCENT_COLOR),
    ("chat_outReplyLine", SOLID_ACCENT_COLOR),
    ("chat_outReplyMessageText", SECONDARY_TEXT_COLOR),
    ("chat_outReplyNameText", PRIMARY_TEXT_COLOR),
    ("chat_outSentCheck", GREEN_500 | SOLID_ALPHA),
    ("chat_outSentCheckSelected", GREEN_500 | SOLID_ALPHA),
    ("chat_outSentClock", GREEN_500 | SOLID_ALPHA),
    ("chat_outSentClockSelected", GREEN_500 | SOLID_ALPHA),
    ("chat_outSiteNameText", PRIMARY_TEXT_COLOR),
    ("chat_outTimeSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_outTimeText", SECONDARY_TEXT_COLOR),
    ("chat_outViews", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_outViewsSelected", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_outVoiceSeekbar", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_outVoiceSeekbarFill", ACTIVE_ICON_COLOR),
    ("chat_outVoiceSeekbarSelected", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_recordedVoiceDot", RED_500 | SOLID_ALPHA),
    ("chat_replyPanelClose", ACTIVE_ICON_COLOR),
    ("chat_replyPanelIcons", ACTIVE_ICON_COLOR),
    ("chat_replyPanelLine", DIVIDER_COLOR),
    ("chat_replyPanelMessage", SECONDARY_TEXT_COLOR),
    ("chat_replyPanelName", PRIMARY_TEXT_COLOR),
    ("chat_reportSpam", RED_500 | SOLID_ALPHA),
    ("chat_selectedBackground", LIGHT_SELECTED_COLOR),
    ("chat_unreadMessagesStartArrowIcon", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("chat_unreadMessagesStartBackground", DIVIDER_COLOR),
    ("chat_unreadMessagesStartText", LIGHT_ACCENT_COLOR | LIGHT_TEXT_SECONDARY_ALPHA),
    ("chat_wallpaper", BACKGROUND_COLOR),
    ("chats_actionBackground", SOLID_ACCENT_COLOR),
    ("chats_actionIcon", ACTIVE_ICON_COLOR),
    ("chats_actionMessage", SOLID_LIGHT_ACCENT_COLOR),
    ("chats_actionPressedBackground", LIGHT_SELECTED_COLOR),
    ("chats_attachMessage", SOLID_LIGHT_ACCENT_COLOR),
    ("chats_date", SECONDARY_TEXT_COLOR),
    ("chats_draft", RED_500 | SOLID_ALPHA),
    ("chats_menuBackground", BACKGROUND_COLOR),
    ("chats_menuCloud", ACTIVE_ICON_COLOR),
    ("chats_menuItemIcon", ACTIVE_ICON_COLOR),
    ("chats_menuItemText", PRIMARY_TEXT_COLOR),
    ("chats_menuName", PRIMARY_TEXT_COLOR),
    ("chats_menuPhone", SECONDARY_TEXT_COLOR),
    ("chats_message", SECONDARY_TEXT_COLOR),
    ("chats_muteIcon", ACTIVE_ICON_COLOR),
    ("chats_name", PRIMARY_TEXT_COLOR),
    ("chats_nameIcon", ACTIVE_ICON_COLOR),
    ("chats_nameMessage", SOLID_LIGHT_ACCENT_COLOR),
    ("chats_pinnedIcon", ACTIVE_ICON_COLOR),
    ("chats_pinnedOverlay", LIGHT_TEXT_COLOR | LIGHT_TEXT_DIVIDER_ALPHA),
    ("chats_sentCheck", GREEN_500 | SOLID_ALPHA),
    ("chats_sentClock", GREEN_500 | SOLID_ALPHA),
    ("chats_sentError", RED_500 | SOLID_ALPHA),
    ("chats_unreadCounter", SOLID_ACCENT_COLOR),
    ("chats_unreadCounterMuted", LIGHT_TEXT_COLOR | LIGHT_TEXT_DIVIDER_ALPHA),
    ("chats_unreadCounterText", PRIMARY_TEXT_COLOR),
    ("chats_verifiedBackground", SOLID_ACCENT_COLOR),
    ("chats_verifiedCheck", ACTIVE_ICON_COLOR),
    ("checkbox", SOLID_ACCENT_COLOR),
    ("checkboxCheck", ACTIVE_ICON_COLOR),
    ("divider", DIVIDER_COLOR),
    ("emptyListPlaceholder", SECONDARY_TEXT_COLOR),
    ("files_folderIcon", DARK_ICON_COLOR | DARK_ICON_ACTIVE_ALPHA),
    ("files_folderIconBackground", LIGHT_BACKGROUND_COLOR | SOLID_ALPHA),
    ("files_iconText", DARK_TEXT_COLOR | DARK_TEXT_PRIMARY_ALPHA),
    ("graySection", DARK_CARD_COLOR | SOLID_ALPHA),
    ("inappPlayerBackground", DARK_CARD_COLOR | SOLID_ALPHA),
    ("inappPlayerClose", ACTIVE_ICON_COLOR),
    ("inappPlayerPerformer", SECONDARY_TEXT_COLOR),
    ("inappPlayerPlayPause", ACTIVE_ICON_COLOR),
    ("inappPlayerTitle", PRIMARY_TEXT_COLOR),
    ("location_sendLocationBackground", SOLID_ACCENT_COLOR),
    ("location_sendLocationIcon", ACTIVE_ICON_COLOR),
    ("profile_actionBackground", SOLID_ACCENT_COLOR),
    ("profile_actionIcon", ACTIVE_ICON_COLOR),
    ("profile_actionPressedBackground", LIGHT_SELECTED_COLOR),
    ("profile_adminIcon", LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA),
    ("profile_creatorIcon", SOLID_ACCENT_COLOR),
    ("profile_title", PRIMARY_TEXT_COLOR),
    ("progressCircle", SOLID_ACCENT_COLOR),
    ("switchThumb", SWITCH_THUMB_OFF_COLOR | SWITCH_THUMB_OFF_ALPHA),
    ("switchThumbChecked", ACCENT_COLOR | SWITCH_THUMB_ON_ALPHA),
    ("switchTrack", SWITCH_TRACK_OFF_COLOR | SWITCH_TRACK_OFF_ALPHA),
    ("switchTrackChecked", ACCENT_COLOR | SWITCH_TRACK_ON_ALPHA),
    ("windowBackgroundGray", DIVIDER_COLOR),
    ("windowBackgroundGrayShadow", BACKGROUND_COLOR),
    ("windowBackgroundWhite", BACKGROUND_COLOR),
    ("windowBackgroundWhiteBlackText", PRIMARY_TEXT_COLOR),
    ("windowBackgroundWhiteBlueHeader", LIGHT_ACCENT_COLOR | LIGHT_TEXT_SECONDARY_ALPHA),
    ("windowBackgroundWhiteBlueText", SOLID_LIGHT_ACCENT_COLOR),
    ("windowBackgroundWhiteGrayIcon", ACTIVE_ICON_COLOR),
    ("windowBackgroundWhiteGrayText", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText2", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText3", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText4", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText5", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteLinkSelection", LIGHT_SELECTED_COLOR),
    ("windowBackgroundWhiteLinkText", SOLID_LIGHT_ACCENT_COLOR),
    ("windowBackgroundWhiteValueText", SECONDARY_TEXT_COLOR),
]


if __name__ == "__main__":
    print_theme(THEME)
