#!/usr/bin/env python3

"""
Material Dark theme generator.
"""

from utils import print_theme, SOLID_ALPHA
from utils.material import *

PRIMARY_ACCENT_COLOR = BLUE_A200
SECONDARY_ACCENT_COLOR = BLUE_A100

SOLID_PRIMARY_ACCENT_COLOR = PRIMARY_ACCENT_COLOR | SOLID_ALPHA
SOLID_SECONDARY_ACCENT_COLOR = SECONDARY_ACCENT_COLOR | SOLID_ALPHA

PRIMARY_TEXT_COLOR = LIGHT_TEXT_COLOR | LIGHT_TEXT_PRIMARY_ALPHA
SECONDARY_TEXT_COLOR = LIGHT_TEXT_COLOR | LIGHT_TEXT_SECONDARY_ALPHA

LIGHT_ACTIVE_ICON_COLOR = LIGHT_ICON_COLOR | LIGHT_ICON_ACTIVE_ALPHA
LIGHT_INACTIVE_ICON_COLOR = LIGHT_ICON_COLOR | LIGHT_ICON_INACTIVE_ALPHA
DARK_ACTIVE_ICON_COLOR = DARK_ICON_COLOR | DARK_ICON_ACTIVE_ALPHA

PRIMARY_BACKGROUND_COLOR = DARK_BACKGROUND_COLOR | SOLID_ALPHA
SECONDARY_BACKGROUND_COLOR = LIGHT_BACKGROUND_COLOR | SOLID_ALPHA

SOLID_CARD_COLOR = DARK_CARD_COLOR | SOLID_ALPHA
APP_BAR_COLOR = DARK_APP_BAR_COLOR | SOLID_ALPHA
DIVIDER_COLOR = LIGHT_TEXT_COLOR | LIGHT_TEXT_DIVIDER_ALPHA
HINT_COLOR = LIGHT_TEXT_COLOR | LIGHT_TEXT_HINT_ALPHA
LIGHT_SELECTED_COLOR = LIGHT_TEXT_COLOR | RIPPLE_ALPHA

THEME = [
    ("actionBarActionModeDefault", APP_BAR_COLOR),
    ("actionBarActionModeDefaultIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("actionBarActionModeDefaultTop", DARK_STATUS_BAR_COLOR | SOLID_ALPHA),
    ("actionBarDefault", APP_BAR_COLOR),
    ("actionBarDefaultIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("actionBarDefaultSearch", PRIMARY_TEXT_COLOR),
    ("actionBarDefaultSearchPlaceholder", HINT_COLOR),
    ("actionBarDefaultSelector", LIGHT_SELECTED_COLOR),
    ("actionBarDefaultSubtitle", SECONDARY_TEXT_COLOR),
    ("actionBarDefaultTitle", PRIMARY_TEXT_COLOR),
    ("avatar_actionBarIconBlue", LIGHT_ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconCyan", LIGHT_ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconGreen", LIGHT_ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconOrange", LIGHT_ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconPink", LIGHT_ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconRed", LIGHT_ACTIVE_ICON_COLOR),
    ("avatar_actionBarIconViolet", LIGHT_ACTIVE_ICON_COLOR),
    ("avatar_actionBarSelectorBlue", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorCyan", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorGreen", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorOrange", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorPink", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorRed", LIGHT_SELECTED_COLOR),
    ("avatar_actionBarSelectorViolet", LIGHT_SELECTED_COLOR),
    ("avatar_backgroundActionBarBlue", BLUE_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarCyan", CYAN_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarGreen", GREEN_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarOrange", ORANGE_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarPink", PINK_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarRed", RED_900 | SOLID_ALPHA),
    ("avatar_backgroundActionBarViolet", PURPLE_900 | SOLID_ALPHA),
    ("avatar_backgroundBlue", BLUE_500 | SOLID_ALPHA),
    ("avatar_backgroundCyan", CYAN_700 | SOLID_ALPHA),
    ("avatar_backgroundGreen", GREEN_500 | SOLID_ALPHA),
    ("avatar_backgroundOrange", ORANGE_800 | SOLID_ALPHA),
    ("avatar_backgroundPink", PINK_500 | SOLID_ALPHA),
    ("avatar_backgroundRed", RED_500 | SOLID_ALPHA),
    ("avatar_backgroundViolet", PURPLE_500 | SOLID_ALPHA),
    ("avatar_nameInMessageBlue", BLUE_400 | SOLID_ALPHA),
    ("avatar_nameInMessageCyan", CYAN_500| SOLID_ALPHA),
    ("avatar_nameInMessageGreen", GREEN_500 | SOLID_ALPHA),
    ("avatar_nameInMessageOrange", ORANGE_500 | SOLID_ALPHA),
    ("avatar_nameInMessagePink", PINK_200 | SOLID_ALPHA),
    ("avatar_nameInMessageRed", RED_300 | SOLID_ALPHA),
    ("avatar_nameInMessageViolet", PURPLE_200 | SOLID_ALPHA),
    ("avatar_subtitleInProfileBlue", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileCyan", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileGreen", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileOrange", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfilePink", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileRed", SECONDARY_TEXT_COLOR),
    ("avatar_subtitleInProfileViolet", SECONDARY_TEXT_COLOR),
    ("avatar_text", PRIMARY_TEXT_COLOR),
    ("chat_botButtonText", PRIMARY_TEXT_COLOR),
    ("chat_botButtonText", PRIMARY_TEXT_COLOR),
    ("chat_botKeyboardButtonBackground", SOLID_CARD_COLOR),
    ("chat_botKeyboardButtonBackgroundPressed", LIGHT_SELECTED_COLOR),
    ("chat_botKeyboardButtonText", PRIMARY_TEXT_COLOR),
    ("chat_botProgress", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_editDoneIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_emojiPanelBackground", PRIMARY_BACKGROUND_COLOR),
    ("chat_emojiPanelBackspace", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_emojiPanelIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_emojiPanelIconSelected", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_emojiPanelIconSelector", LIGHT_SELECTED_COLOR),
    ("chat_emojiPanelNewTrending", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_emojiPanelShadowLine", PRIMARY_BACKGROUND_COLOR),
    ("chat_emojiPanelStickerPackSelector", LIGHT_SELECTED_COLOR),
    ("chat_emojiPanelTrendingDescription", SECONDARY_TEXT_COLOR),
    ("chat_emojiPanelTrendingTitle", PRIMARY_TEXT_COLOR),
    ("chat_goDownButton", SECONDARY_BACKGROUND_COLOR),
    ("chat_goDownButtonCounter", PRIMARY_TEXT_COLOR),
    ("chat_goDownButtonCounterBackground", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_goDownButtonIcon", DARK_TEXT_COLOR | DARK_ICON_ACTIVE_ALPHA),
    ("chat_goDownButtonShadow", PRIMARY_BACKGROUND_COLOR),
    ("chat_inAudioDurationSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_inAudioDurationText", SECONDARY_TEXT_COLOR),
    ("chat_inAudioPerfomerText", SECONDARY_TEXT_COLOR),
    ("chat_inAudioPerformerText", SECONDARY_TEXT_COLOR),
    ("chat_inAudioSeekbar", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_inAudioSeekbarFill", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_inAudioSeekbarSelected", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_inAudioTitleText", PRIMARY_TEXT_COLOR),
    ("chat_inBubble", SOLID_CARD_COLOR),
    ("chat_inBubbleSelected", LIGHT_SELECTED_COLOR),
    ("chat_inBubbleShadow", PRIMARY_BACKGROUND_COLOR),
    ("chat_inContactBackground", SECONDARY_BACKGROUND_COLOR),
    ("chat_inContactIcon", DARK_ACTIVE_ICON_COLOR),
    ("chat_inContactNameText", PRIMARY_TEXT_COLOR),
    ("chat_inContactPhoneText", SECONDARY_TEXT_COLOR),
    ("chat_inFileInfoSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_inFileInfoText", SECONDARY_TEXT_COLOR),
    ("chat_inFileNameText", PRIMARY_TEXT_COLOR),
    ("chat_inForwardedNameText", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_inInstant", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_inInstantSelected", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_inLoader", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_inLoaderSelected", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_inLocationBackground", SOLID_CARD_COLOR),
    ("chat_inLocationIcon", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_inPreviewInstantSelectedText", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_inPreviewInstantText", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_inPreviewLine", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_inReplyLine", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_inReplyMessageText", SECONDARY_TEXT_COLOR),
    ("chat_inReplyNameText", PRIMARY_TEXT_COLOR),
    ("chat_inSiteNameText", PRIMARY_TEXT_COLOR),
    ("chat_inTimeSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_inTimeText", SECONDARY_TEXT_COLOR),
    ("chat_inVenueInfoSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_inVenueInfoText", SECONDARY_TEXT_COLOR),
    ("chat_inVenueNameText", PRIMARY_TEXT_COLOR),
    ("chat_inViews", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_inViewsSelected", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_inVoiceSeekbar", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_inVoiceSeekbarFill", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_inVoiceSeekbarSelected", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_linkSelectBackground", LIGHT_SELECTED_COLOR),
    ("chat_messageLinkIn", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_messageLinkOut", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_messagePanelBackground", SOLID_CARD_COLOR),
    ("chat_messagePanelHint", HINT_COLOR),
    ("chat_messagePanelIcons", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_messagePanelSend", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_messagePanelShadow", PRIMARY_BACKGROUND_COLOR),
    ("chat_messagePanelText", PRIMARY_TEXT_COLOR),
    ("chat_messagePanelVoicePressed", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_messageTextIn", PRIMARY_TEXT_COLOR),
    ("chat_messageTextOut", PRIMARY_TEXT_COLOR),
    ("chat_muteIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_outAudioDurationSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_outAudioDurationText", SECONDARY_TEXT_COLOR),
    ("chat_outAudioPerfomerText", SECONDARY_TEXT_COLOR),
    ("chat_outAudioPerformerText", SECONDARY_TEXT_COLOR),
    ("chat_outAudioSeekbar", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_outAudioSeekbarFill", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_outAudioSeekbarSelected", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_outAudioTitleText", PRIMARY_TEXT_COLOR),
    ("chat_outBubble", GREY_700 | SOLID_ALPHA),
    ("chat_outBubbleSelected", LIGHT_SELECTED_COLOR),
    ("chat_outBubbleShadow", PRIMARY_BACKGROUND_COLOR),
    ("chat_outContactBackground", SECONDARY_BACKGROUND_COLOR),
    ("chat_outContactIcon", DARK_ACTIVE_ICON_COLOR),
    ("chat_outContactNameText", PRIMARY_TEXT_COLOR),
    ("chat_outContactPhoneText", SECONDARY_TEXT_COLOR),
    ("chat_outFileInfoSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_outFileInfoText", SECONDARY_TEXT_COLOR),
    ("chat_outFileNameText", PRIMARY_TEXT_COLOR),
    ("chat_outForwardedNameText", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_outInstant", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_outInstantSelected", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_outLoader", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_outLoaderSelected", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_outLocationBackground", SOLID_CARD_COLOR),
    ("chat_outLocationIcon", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_outMenu", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_outMenuSelected", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_outPreviewInstantSelectedText", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_outPreviewInstantText", SOLID_SECONDARY_ACCENT_COLOR),
    ("chat_outPreviewLine", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_outReplyLine", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_outReplyMessageText", SECONDARY_TEXT_COLOR),
    ("chat_outReplyNameText", PRIMARY_TEXT_COLOR),
    ("chat_outSentCheck", GREEN_500 | SOLID_ALPHA),
    ("chat_outSentCheckSelected", GREEN_500 | SOLID_ALPHA),
    ("chat_outSentClock", GREEN_500 | SOLID_ALPHA),
    ("chat_outSentClockSelected", GREEN_500 | SOLID_ALPHA),
    ("chat_outSiteNameText", PRIMARY_TEXT_COLOR),
    ("chat_outTimeSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_outTimeText", SECONDARY_TEXT_COLOR),
    ("chat_outVenueInfoSelectedText", SECONDARY_TEXT_COLOR),
    ("chat_outVenueInfoText", SECONDARY_TEXT_COLOR),
    ("chat_outVenueNameText", SECONDARY_TEXT_COLOR),
    ("chat_outViews", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_outViewsSelected", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_outVoiceSeekbar", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_outVoiceSeekbarFill", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_outVoiceSeekbarSelected", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_recordedVoiceDot", RED_500 | SOLID_ALPHA),
    ("chat_recordTime", PRIMARY_TEXT_COLOR),
    ("chat_recordVoiceCancel", SECONDARY_TEXT_COLOR),
    ("chat_replyPanelClose", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_replyPanelIcons", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_replyPanelLine", DIVIDER_COLOR),
    ("chat_replyPanelMessage", SECONDARY_TEXT_COLOR),
    ("chat_replyPanelName", PRIMARY_TEXT_COLOR),
    ("chat_reportSpam", RED_500 | SOLID_ALPHA),
    ("chat_selectedBackground", LIGHT_SELECTED_COLOR),
    ("chat_stickersHintPanel", SOLID_CARD_COLOR),
    ("chat_topPanelBackground", SOLID_CARD_COLOR),
    ("chat_topPanelClose", LIGHT_ACTIVE_ICON_COLOR),
    ("chat_topPanelLine", SOLID_PRIMARY_ACCENT_COLOR),
    ("chat_topPanelMessage", SECONDARY_TEXT_COLOR),
    ("chat_topPanelTitle", PRIMARY_TEXT_COLOR),
    ("chat_unreadMessagesStartArrowIcon", LIGHT_INACTIVE_ICON_COLOR),
    ("chat_unreadMessagesStartBackground", DIVIDER_COLOR),
    ("chat_unreadMessagesStartText", SECONDARY_ACCENT_COLOR | LIGHT_TEXT_SECONDARY_ALPHA),
    ("chat_wallpaper", PRIMARY_BACKGROUND_COLOR),
    ("chats_actionBackground", SOLID_PRIMARY_ACCENT_COLOR),
    ("chats_actionIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("chats_actionMessage", SOLID_SECONDARY_ACCENT_COLOR),
    ("chats_actionPressedBackground", LIGHT_SELECTED_COLOR),
    ("chats_attachMessage", SOLID_SECONDARY_ACCENT_COLOR),
    ("chats_date", SECONDARY_TEXT_COLOR),
    ("chats_draft", RED_500 | SOLID_ALPHA),
    ("chats_menuBackground", PRIMARY_BACKGROUND_COLOR),
    ("chats_menuCloud", LIGHT_ACTIVE_ICON_COLOR),
    ("chats_menuItemIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("chats_menuItemText", PRIMARY_TEXT_COLOR),
    ("chats_menuName", PRIMARY_TEXT_COLOR),
    ("chats_menuPhone", SECONDARY_TEXT_COLOR),
    ("chats_message", SECONDARY_TEXT_COLOR),
    ("chats_muteIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("chats_name", PRIMARY_TEXT_COLOR),
    ("chats_nameIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("chats_nameMessage", SOLID_SECONDARY_ACCENT_COLOR),
    ("chats_pinnedIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("chats_pinnedOverlay", LIGHT_TEXT_COLOR | LIGHT_TEXT_DIVIDER_ALPHA),
    ("chats_sentCheck", GREEN_500 | SOLID_ALPHA),
    ("chats_sentClock", GREEN_500 | SOLID_ALPHA),
    ("chats_sentError", RED_500 | SOLID_ALPHA),
    ("chats_unreadCounter", SOLID_PRIMARY_ACCENT_COLOR),
    ("chats_unreadCounterMuted", LIGHT_TEXT_COLOR | LIGHT_TEXT_DIVIDER_ALPHA),
    ("chats_unreadCounterText", PRIMARY_TEXT_COLOR),
    ("chats_verifiedBackground", SOLID_PRIMARY_ACCENT_COLOR),
    ("chats_verifiedCheck", LIGHT_ACTIVE_ICON_COLOR),
    ("checkbox", SOLID_PRIMARY_ACCENT_COLOR),
    ("checkboxCheck", LIGHT_ACTIVE_ICON_COLOR),
    ("divider", DIVIDER_COLOR),
    ("emptyListPlaceholder", SECONDARY_TEXT_COLOR),
    ("fastScrollActive", SOLID_PRIMARY_ACCENT_COLOR),
    ("fastScrollInactive", GREY_700 | SOLID_ALPHA),
    ("featuredStickers_addButton", SOLID_SECONDARY_ACCENT_COLOR),
    ("featuredStickers_addButtonPressed", SOLID_PRIMARY_ACCENT_COLOR),
    ("featuredStickers_addedIcon", LIGHT_INACTIVE_ICON_COLOR),
    ("files_folderIcon", DARK_ACTIVE_ICON_COLOR),
    ("files_folderIconBackground", SECONDARY_BACKGROUND_COLOR),
    ("files_iconText", DARK_TEXT_COLOR | DARK_TEXT_PRIMARY_ALPHA),
    ("graySection", SOLID_CARD_COLOR),
    ("groupcreate_checkbox", LIGHT_ACTIVE_ICON_COLOR),
    ("groupcreate_checkbox", SOLID_PRIMARY_ACCENT_COLOR),
    ("groupcreate_cursor", PRIMARY_TEXT_COLOR),
    ("groupcreate_hintText", HINT_COLOR),
    ("groupcreate_offlineText", SECONDARY_TEXT_COLOR),
    ("groupcreate_onlineText", SOLID_SECONDARY_ACCENT_COLOR),
    ("groupcreate_sectionText", SOLID_SECONDARY_ACCENT_COLOR),
    ("groupcreate_spanBackground", SOLID_CARD_COLOR),
    ("groupcreate_spanText", PRIMARY_TEXT_COLOR),
    ("inappPlayerBackground", SOLID_CARD_COLOR),
    ("inappPlayerClose", LIGHT_ACTIVE_ICON_COLOR),
    ("inappPlayerPerformer", SECONDARY_TEXT_COLOR),
    ("inappPlayerPlayPause", LIGHT_ACTIVE_ICON_COLOR),
    ("inappPlayerTitle", PRIMARY_TEXT_COLOR),
    ("listSelector", LIGHT_SELECTED_COLOR),
    ("listSelectorSDK21", LIGHT_SELECTED_COLOR),
    ("location_sendLocationBackground", SOLID_PRIMARY_ACCENT_COLOR),
    ("location_sendLocationIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("musicPicker_buttonBackground", SECONDARY_BACKGROUND_COLOR),
    ("musicPicker_buttonIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("musicPicker_checkbox", SOLID_PRIMARY_ACCENT_COLOR),
    ("musicPicker_checkboxCheck", LIGHT_ACTIVE_ICON_COLOR),
    ("picker_badge", SOLID_PRIMARY_ACCENT_COLOR),
    ("picker_badgeText", PRIMARY_TEXT_COLOR),
    ("picker_disabledButton", LIGHT_TEXT_COLOR | LIGHT_TEXT_DISABLED_ALPHA),
    ("picker_enabledButton", SOLID_PRIMARY_ACCENT_COLOR),
    ("profile_actionBackground", SOLID_PRIMARY_ACCENT_COLOR),
    ("profile_actionIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("profile_actionPressedBackground", LIGHT_SELECTED_COLOR),
    ("profile_adminIcon", LIGHT_INACTIVE_ICON_COLOR),
    ("profile_creatorIcon", SOLID_PRIMARY_ACCENT_COLOR),
    ("profile_title", PRIMARY_TEXT_COLOR),
    ("progressCircle", LIGHT_INACTIVE_ICON_COLOR),
    ("stickers_menu", LIGHT_ACTIVE_ICON_COLOR),
    ("stickers_menuSelector", LIGHT_SELECTED_COLOR),
    ("switchThumb", SWITCH_THUMB_OFF_COLOR | SWITCH_THUMB_OFF_ALPHA),
    ("switchThumbChecked", PRIMARY_ACCENT_COLOR | SWITCH_THUMB_ON_ALPHA),
    ("switchTrack", SWITCH_TRACK_OFF_COLOR | SWITCH_TRACK_OFF_ALPHA),
    ("switchTrackChecked", PRIMARY_ACCENT_COLOR | SWITCH_TRACK_ON_ALPHA),
    ("windowBackgroundGray", DIVIDER_COLOR),
    ("windowBackgroundGrayShadow", PRIMARY_BACKGROUND_COLOR),
    ("windowBackgroundWhite", PRIMARY_BACKGROUND_COLOR),
    ("windowBackgroundWhiteBlackText", PRIMARY_TEXT_COLOR),
    ("windowBackgroundWhiteBlueHeader", SECONDARY_ACCENT_COLOR | LIGHT_TEXT_SECONDARY_ALPHA),
    ("windowBackgroundWhiteBlueText", SOLID_SECONDARY_ACCENT_COLOR),
    ("windowBackgroundWhiteBlueText2", SOLID_SECONDARY_ACCENT_COLOR),
    ("windowBackgroundWhiteBlueText3", SOLID_SECONDARY_ACCENT_COLOR),
    ("windowBackgroundWhiteBlueText4", SOLID_SECONDARY_ACCENT_COLOR),
    ("windowBackgroundWhiteBlueText5", SOLID_SECONDARY_ACCENT_COLOR),
    ("windowBackgroundWhiteBlueText6", SOLID_SECONDARY_ACCENT_COLOR),
    ("windowBackgroundWhiteBlueText7", SOLID_SECONDARY_ACCENT_COLOR),
    ("windowBackgroundWhiteGrayIcon", LIGHT_ACTIVE_ICON_COLOR),
    ("windowBackgroundWhiteGrayLine", HINT_COLOR),
    ("windowBackgroundWhiteGrayText", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText2", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText3", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText4", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText5", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText6", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText7", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGrayText8", SECONDARY_TEXT_COLOR),
    ("windowBackgroundWhiteGreenText", GREEN_500 | SOLID_ALPHA),
    ("windowBackgroundWhiteHintText", HINT_COLOR),
    ("windowBackgroundWhiteInputField", HINT_COLOR),
    ("windowBackgroundWhiteInputFieldActivated", SOLID_PRIMARY_ACCENT_COLOR),
    ("windowBackgroundWhiteLinkSelection", LIGHT_SELECTED_COLOR),
    ("windowBackgroundWhiteLinkText", SOLID_SECONDARY_ACCENT_COLOR),
    ("windowBackgroundWhiteRedText", RED_500 | SOLID_ALPHA),
    ("windowBackgroundWhiteRedText2", RED_500 | SOLID_ALPHA),
    ("windowBackgroundWhiteRedText3", RED_500 | SOLID_ALPHA),
    ("windowBackgroundWhiteRedText4", RED_500 | SOLID_ALPHA),
    ("windowBackgroundWhiteValueText", SECONDARY_TEXT_COLOR),
]


if __name__ == "__main__":
    print_theme(THEME)
